version: 2.1

commands:
  restore_module_cache:
    parameters:
      module_path:
        type: string
    steps:
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-<< parameters.module_path >>-{{ checksum "<< parameters.module_path >>/yarn.lock" }}
  save_module_cache:
    parameters:
      module_path:
        type: string
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-<< parameters.module_path >>-{{ checksum "<< parameters.module_path >>/yarn.lock" }}
          paths:
            - << parameters.module_path >>/node_modules

  setup_and_test:
    steps:
      - checkout
      - restore_module_cache: { module_path: ./ }
      - run:
          name: Install Dependencies
          command: yarn
      - save_module_cache: { module_path: ./ }
      # - run: yarn type-check # Uncomment when implemented
      - run:
          name: Lint Files
          command: yarn lint
      # - run: yarn test # Uncomment when implemented
      - run:
          name: Build
          command: yarn build
jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app
    steps:
      - setup_and_test

workflows:
  version: 2.1
  test_workflow:
    jobs:
      - test
